spring:
  application:
    name: ecommerce-backend

  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

success-url: https://api.kimjeongmo.shop/auth/callback
failure-url: https://api.kimjeongmo.shop/auth/error

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,https://api.kimjeongmo.shop